// ==========================================
// Bilingual Content Data
// ==========================================

const FLASHCARD_DATA = {
  fruits: [
    { emoji: '🍎', zh: '苹果', en: 'Apple', pinyin: 'píng guǒ', phonetic: 'AP-uhl' },
    { emoji: '🍌', zh: '香蕉', en: 'Banana', pinyin: 'xiāng jiāo', phonetic: 'buh-NA-nuh' },
    { emoji: '🍊', zh: '橘子', en: 'Orange', pinyin: 'jú zi', phonetic: 'OR-inj' },
    { emoji: '🍇', zh: '葡萄', en: 'Grape', pinyin: 'pú tao', phonetic: 'GRAYP' },
    { emoji: '🍓', zh: '草莓', en: 'Strawberry', pinyin: 'cǎo méi', phonetic: 'STRAW-bair-ee' },
    { emoji: '🍉', zh: '西瓜', en: 'Watermelon', pinyin: 'xī guā', phonetic: 'WAW-tair-mel-uhn' },
    { emoji: '🍑', zh: '桃子', en: 'Peach', pinyin: 'táo zi', phonetic: 'PEECH' },
    { emoji: '🍒', zh: '樱桃', en: 'Cherry', pinyin: 'yīng tao', phonetic: 'CHAIR-ee' },
    { emoji: '🥝', zh: '猕猴桃', en: 'Kiwi', pinyin: 'mí hóu táo', phonetic: 'KEE-wee' },
    { emoji: '🍋', zh: '柠檬', en: 'Lemon', pinyin: 'níng méng', phonetic: 'LEM-uhn' },
  ],
  body: [
    { emoji: '👀', zh: '眼睛', en: 'Eyes', pinyin: 'yǎn jing', phonetic: 'YZ' },
    { emoji: '👃', zh: '鼻子', en: 'Nose', pinyin: 'bí zi', phonetic: 'NOHZ' },
    { emoji: '👄', zh: '嘴巴', en: 'Mouth', pinyin: 'zuǐ ba', phonetic: 'MOWTH' },
    { emoji: '👂', zh: '耳朵', en: 'Ears', pinyin: 'ěr duo', phonetic: 'EERZ' },
    { emoji: '🤚', zh: '手', en: 'Hand', pinyin: 'shǒu', phonetic: 'HAND' },
    { emoji: '🦶', zh: '脚', en: 'Foot', pinyin: 'jiǎo', phonetic: 'FUT' },
    { emoji: '🦷', zh: '牙齿', en: 'Teeth', pinyin: 'yá chǐ', phonetic: 'TEETH' },
    { emoji: '💆', zh: '头', en: 'Head', pinyin: 'tóu', phonetic: 'HED' },
    { emoji: '🫀', zh: '心脏', en: 'Heart', pinyin: 'xīn zàng', phonetic: 'HART' },
    { emoji: '🦴', zh: '骨头', en: 'Bone', pinyin: 'gǔ tou', phonetic: 'BOHN' },
  ],
  family: [
    { emoji: '👨', zh: '爸爸', en: 'Dad', pinyin: 'bà ba', phonetic: 'DAD' },
    { emoji: '👩', zh: '妈妈', en: 'Mom', pinyin: 'mā ma', phonetic: 'MOM' },
    { emoji: '👴', zh: '爷爷', en: 'Grandpa', pinyin: 'yé ye', phonetic: 'GRAN-pah' },
    { emoji: '👵', zh: '奶奶', en: 'Grandma', pinyin: 'nǎi nai', phonetic: 'GRAN-mah' },
    { emoji: '👦', zh: '哥哥', en: 'Brother', pinyin: 'gē ge', phonetic: 'BRUTH-er' },
    { emoji: '👧', zh: '姐姐', en: 'Sister', pinyin: 'jiě jie', phonetic: 'SIS-tair' },
    { emoji: '👶', zh: '宝宝', en: 'Baby', pinyin: 'bǎo bao', phonetic: 'BAY-bee' },
    { emoji: '👨‍👩‍👧‍👦', zh: '家庭', en: 'Family', pinyin: 'jiā tíng', phonetic: 'FAM-uh-lee' },
    { emoji: '👶🏻', zh: '弟弟', en: 'Little Brother', pinyin: 'dì di', phonetic: 'LID-uhl BRUTH-er' },
    { emoji: '👧🏻', zh: '妹妹', en: 'Little Sister', pinyin: 'mèi mei', phonetic: 'LID-uhl SIS-tair' },
  ],
  nature: [
    { emoji: '☀️', zh: '太阳', en: 'Sun', pinyin: 'tài yáng', phonetic: 'SUN' },
    { emoji: '🌙', zh: '月亮', en: 'Moon', pinyin: 'yuè liang', phonetic: 'MOON' },
    { emoji: '⭐', zh: '星星', en: 'Star', pinyin: 'xīng xing', phonetic: 'STAR' },
    { emoji: '🌈', zh: '彩虹', en: 'Rainbow', pinyin: 'cǎi hóng', phonetic: 'RAYN-boh' },
    { emoji: '🌊', zh: '海洋', en: 'Ocean', pinyin: 'hǎi yáng', phonetic: 'OH-shuhn' },
    { emoji: '⛰️', zh: '山', en: 'Mountain', pinyin: 'shān', phonetic: 'MOUN-tuhn' },
    { emoji: '🌧️', zh: '雨', en: 'Rain', pinyin: 'yǔ', phonetic: 'RAYN' },
    { emoji: '❄️', zh: '雪', en: 'Snow', pinyin: 'xuě', phonetic: 'SNOH' },
    { emoji: '🌸', zh: '花', en: 'Flower', pinyin: 'huā', phonetic: 'FLOW-air' },
    { emoji: '🌳', zh: '树', en: 'Tree', pinyin: 'shù', phonetic: 'TREE' },
  ],
  food: [
    { emoji: '🍚', zh: '米饭', en: 'Rice', pinyin: 'mǐ fàn', phonetic: 'RYS' },
    { emoji: '🍜', zh: '面条', en: 'Noodles', pinyin: 'miàn tiáo', phonetic: 'NOO-duhlz' },
    { emoji: '🥟', zh: '饺子', en: 'Dumpling', pinyin: 'jiǎo zi', phonetic: 'DUMP-ling' },
    { emoji: '🍞', zh: '面包', en: 'Bread', pinyin: 'miàn bāo', phonetic: 'BRED' },
    { emoji: '🥚', zh: '鸡蛋', en: 'Egg', pinyin: 'jī dàn', phonetic: 'EG' },
    { emoji: '🥛', zh: '牛奶', en: 'Milk', pinyin: 'niú nǎi', phonetic: 'MILK' },
    { emoji: '🍦', zh: '冰淇淋', en: 'Ice Cream', pinyin: 'bīng qí lín', phonetic: 'YS KREEM' },
    { emoji: '🍕', zh: '披萨', en: 'Pizza', pinyin: 'pī sà', phonetic: 'PEET-suh' },
    { emoji: '🥗', zh: '沙拉', en: 'Salad', pinyin: 'shā lā', phonetic: 'SAL-uhd' },
    { emoji: '🍵', zh: '茶', en: 'Tea', pinyin: 'chá', phonetic: 'TEE' },
  ],
};

const NUMBER_DATA = {
  1:  { zh: '一', en: 'One',   emoji: '🐻' },
  2:  { zh: '二', en: 'Two',   emoji: '🐥' },
  3:  { zh: '三', en: 'Three', emoji: '🐷' },
  4:  { zh: '四', en: 'Four',  emoji: '🐸' },
  5:  { zh: '五', en: 'Five',  emoji: '🐵' },
  6:  { zh: '六', en: 'Six',   emoji: '🐟' },
  7:  { zh: '七', en: 'Seven', emoji: '🐝' },
  8:  { zh: '八', en: 'Eight', emoji: '🐰' },
  9:  { zh: '九', en: 'Nine',  emoji: '🦋' },
  10: { zh: '十', en: 'Ten',   emoji: '🌟' },
};

const COLOR_DATA = [
  { zh: '红色', en: 'Red',    hex: '#E74C3C' },
  { zh: '橙色', en: 'Orange', hex: '#E67E22' },
  { zh: '黄色', en: 'Yellow', hex: '#F1C40F' },
  { zh: '绿色', en: 'Green',  hex: '#2ECC71' },
  { zh: '蓝色', en: 'Blue',   hex: '#3498DB' },
  { zh: '紫色', en: 'Purple', hex: '#9B59B6' },
  { zh: '粉色', en: 'Pink',   hex: '#E91E8C' },
  { zh: '棕色', en: 'Brown',  hex: '#8B6914' },
  { zh: '黑色', en: 'Black',  hex: '#2C3E50' },
  { zh: '白色', en: 'White',  hex: '#ECF0F1' },
  { zh: '灰色', en: 'Gray',   hex: '#95A5A6' },
  { zh: '金色', en: 'Gold',   hex: '#D4AC0D' },
];

const ANIMAL_DATA = [
  { emoji: '🐱', zh: '猫',   en: 'Cat',   sound_zh: '喵喵', sound_en: 'Meow' },
  { emoji: '🐶', zh: '狗',   en: 'Dog',   sound_zh: '汪汪', sound_en: 'Woof' },
  { emoji: '🐮', zh: '牛',   en: 'Cow',   sound_zh: '哞哞', sound_en: 'Moo' },
  { emoji: '🐷', zh: '猪',   en: 'Pig',   sound_zh: '哼哼', sound_en: 'Oink' },
  { emoji: '🐔', zh: '鸡',   en: 'Chicken', sound_zh: '咯咯', sound_en: 'Cluck' },
  { emoji: '🐸', zh: '青蛙', en: 'Frog',  sound_zh: '呱呱', sound_en: 'Ribbit' },
  { emoji: '🦁', zh: '狮子', en: 'Lion',  sound_zh: '吼',  sound_en: 'Roar' },
  { emoji: '🐘', zh: '大象', en: 'Elephant', sound_zh: '(甩鼻子)', sound_en: 'Trumpet' },
  { emoji: '🐒', zh: '猴子', en: 'Monkey', sound_zh: '吱吱', sound_en: 'Ooh ooh' },
  { emoji: '🐰', zh: '兔子', en: 'Rabbit', sound_zh: '(蹦蹦跳)', sound_en: 'Hop hop' },
  { emoji: '🐟', zh: '鱼',   en: 'Fish',  sound_zh: '(吐泡泡)', sound_en: 'Blub blub' },
  { emoji: '🦋', zh: '蝴蝶', en: 'Butterfly', sound_zh: '(翩翩飞)', sound_en: 'Flutter' },
  { emoji: '🐢', zh: '乌龟', en: 'Turtle', sound_zh: '(慢吞吞)', sound_en: 'Slow and steady' },
  { emoji: '🐧', zh: '企鹅', en: 'Penguin', sound_zh: '(摇摇摆)', sound_en: 'Waddle waddle' },
  { emoji: '🦊', zh: '狐狸', en: 'Fox',   sound_zh: '(偷偷看)', sound_en: 'What does the fox say?' },
  { emoji: '🐼', zh: '熊猫', en: 'Panda', sound_zh: '(啃竹子)', sound_en: 'Nom nom' },
];

const SHAPE_DATA = [
  { zh: '圆形',   en: 'Circle',   svg: '<circle cx="60" cy="60" r="50" />' },
  { zh: '正方形', en: 'Square',   svg: '<rect x="10" y="10" width="100" height="100" />' },
  { zh: '三角形', en: 'Triangle', svg: '<polygon points="60,10 110,110 10,110" />' },
  { zh: '长方形', en: 'Rectangle', svg: '<rect x="5" y="25" width="110" height="70" />' },
  { zh: '菱形',   en: 'Diamond',  svg: '<polygon points="60,5 115,60 60,115 5,60" />' },
  { zh: '椭圆形', en: 'Oval',     svg: '<ellipse cx="60" cy="60" rx="55" ry="35" />' },
  { zh: '五角星', en: 'Star',     svg: '<polygon points="60,5 73,42 112,42 80,65 91,102 60,80 29,102 40,65 8,42 47,42" />' },
  { zh: '心形',   en: 'Heart',    svg: '<path d="M60,100 C10,60 0,20 30,20 C45,20 55,35 60,45 C65,35 75,20 90,20 C120,20 110,60 60,100Z" />' },
];
